export const ACTION_CHANGE_DIFFICULTY = 'ACTION_CHANGE_DIFFICULTY';
export const ACTION_CHANGE_CARD_THEME = 'ACTION_CHANGE_CARD_THEME';
export const ACTION_CHANGE_CURRENT_IMAGES = 'ACTION_CHANGE_CURRENT_IMAGES';
export const ACTION_CHANGE_FIELD_CSS_CLASS = 'ACTION_CHANGE_FIELD_CSS_CLASS';
